module.exports = {
  DEFAULT: "There is some issue",
  USER_NOT_FOUND: "User not found",
  ID_MISSING: "ID missing",
  USER_EXISTS: "User already exists",
  FIND_FILTER_MISSING: "Search filter missing",
  UPDATE_FILTER_MISSING: "Update By filter missing",
  UPDATE_BODY_EMPTY: "Update Body missing",
  BODY_EMPTY: "Insert body missing",
  TOKEN_EXISTS: "Token already exists",
  TOKEN_NOT_FOUND: "Token not found",
  DUPLICATE_DATA_FOUND: "Duplicate data Found",
  NON_EXISTING: "Existing Data not found",
  CANT_DELETE_DEFAULT: "Current Address cannot be deleted",
  CANT_PROCESS_REQUEST: "Request can't be processed",
};
